[WIP] Reuse config base stores
VIISON/shopware-4 pull request #36
Opened 2017-05-15 10:49 UTC by fixpunkt

## Description

Right now, when opening a basic settings plugin configuration page that uses base stores, each base store is loaded `2 * m * n` times, where `m` is the number of config elements that use that base store and `n` is the number of configured sub-shops. This causes an exceedingly large number of redundant requests to be made. Here is an example waterfall graph for loading one of our plugins' settings pages in the default configuration with DE and EN shops:

![image](https://cloud.githubusercontent.com/assets/2817302/26054304/55402926-396c-11e7-9c5a-0a3e5d18bc2d.png)

For users who have more shops defined, loading that plugin's settings page can easily cause over 200 requests, which basically amounts to a small DoS attack against the shop and can lead to errors being returned by the server.

This PR fixes that problem by loading each base store at most once and re-using the fetched data for every config field.
 

| Questions               | Answers |
|-------------------------|-------------------------------------------------------|
| Why?                    | See explanation above. |
| BC breaks?              | no |
| Tests exists & pass?    | none exist |
| Related tickets?        | None that I know of|
| How to test?            | TODO Please describe how to best verify that this PR is correct. |
| Requirements met?       | yes |

2017-05-15 16:06 UTC, svenmuennich requested changes

2017-05-15 16:06 UTC, svenmuennich commented on themes/Backend/ExtJs/backend/base/component/element/select.js
> +        if (!store) {
Maybe we should use an early `return` to reduce indentation.

2017-05-16 07:47 UTC, fixpunkt commented on themes/Backend/ExtJs/backend/base/component/element/select.js
> +        if (!store) {
Good idea

2017-05-16 07:49 UTC, fixpunkt commented
@samuelvogel do you have any ideas on how we can make the PR description more compelling so Shopware merges it faster?

2017-05-16 11:02 UTC, closed without merging