Pickware/handle mail error when saving order
VIISON/shopware-4 pull request #76
Opened 2018-04-17 14:59 UTC by windaishi

This PR is stronly related to https://github.com/shopware/shopware/pull/1496 and requires it to be merged first.

### 1. Why is this change necessary?
When changing the status of an order to a status with a mail template and this mail template is corrupted, the saving of the order fails 'hardly' with an expection. The order gets saved correctly but no after-hooks are executed. Together with Shopware ERP (Powered by Pickware) this leads to serious stock errors that are hard to identify.

### 2. What does this change do, exactly?
Catch any exceptions that occur during the mail creation and forwards the error as a warning to the backend user.

### 3. Describe each step to reproduce the issue or behaviour.
Corrupt a status mail template, for example by adding a '{if}' tag without a closing '{/if}' tag.
Change the status of an order that would send this mail template on status change.
![image](https://user-images.githubusercontent.com/6232639/38878218-b832a920-4260-11e8-9b51-30e35d832e36.png)

### 4. Please link to the relevant issues (if any).
N/A

### 5. Which documentation changes (if any) need to be made because of this PR?
N/A

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2018-04-18 16:59 UTC, fixpunkt requested changes
Nice work!

I've updated the title and the description.

Please remember to always change the PR title from the default value (i.e. the branch name) to something more descriptive when opening PRs.

2018-04-18 16:59 UTC, fixpunkt commented on engine/Shopware/Controllers/Backend/Order.php
> +                    $namespace->get('save_order_failed', 'Error when saving the order. Error: %s'),
`when saving` -> `while trying to save`

2018-04-18 16:59 UTC, fixpunkt commented on engine/Shopware/Controllers/Backend/Order.php
> +                // The method '$this->checkOrderStatus()' (even its name would not imply that) sends mails and can fail
Please remove the passive-aggressive text in parentheses and re-wrap the comment 😉

2018-04-18 16:59 UTC, fixpunkt commented on snippets/backend/order/controller/main.ini
> +save_order_failed = "Error when saving the order. Error: %s"
`when saving` -> `while trying to save`

2018-04-18 16:59 UTC, fixpunkt commented on snippets/backend/order/controller/main.ini
> +send_mail_failed = "Error when sending mail. Error: %s"
`when sending mail` -> `while trying to send an email`

2018-04-18 16:59 UTC, fixpunkt commented on engine/Shopware/Controllers/Backend/Order.php
> +                    $namespace->get('send_mail_failed', 'Error when sending mail. Error: %s'),
`when sending mail` -> `while trying to send an email`

2018-04-18 16:59 UTC, fixpunkt commented on snippets/backend/order/main.ini
> +batch/order_error/title = "Error at order [0]"
`Error processing order [0]`

2018-04-18 16:59 UTC, fixpunkt commented on themes/Backend/ExtJs/backend/order/controller/batch.js
> +        orderErrorTitle: '{s name=batch/order_error/title}Error at order [0]{/s}',
`at` -> `processing`

2018-04-18 16:59 UTC, fixpunkt commented on themes/Backend/ExtJs/backend/order/controller/batch.js
> +                Ext.Array.forEach(resultSet, function (batchResult) {
Please add a comment above this line explaining what happens here.

2018-04-18 16:59 UTC, fixpunkt commented on themes/Backend/ExtJs/backend/order/controller/batch.js
> +        if (resultRecord.get('success') === false) {
Is the `=== false` really necessary? `!resultRecord.get('success')` should be just fine too!

2018-04-18 16:59 UTC, fixpunkt commented on engine/Shopware/Controllers/Backend/Order.php
> +                $mail = null;
Redundant assignment.

2018-04-18 16:59 UTC, fixpunkt commented on engine/Shopware/Controllers/Backend/Order.php
> +        foreach ($orders as &$data) {
Is it really necessary to change this loop to use references? I'd avoid this like hell tbh.

2018-04-18 16:59 UTC, fixpunkt commented on engine/Shopware/Controllers/Backend/Order.php
> +                $data['errorMessage'] = $namespace->get('no_order_id_passed', 'No valid order id passed.');
Is this really an error we need to report back to the user? From reading the code, this looks like a sanity check but shouldn't really happen in production?

2018-04-18 16:59 UTC, fixpunkt commented on engine/Shopware/Controllers/Backend/Order.php
> +                $data['errorMessage'] = $namespace->get('no_order_id_passed', 'No valid order id passed.');
Same here.

2018-04-20 13:58 UTC, windaishi commented
Actually you reviewed the wrong PR :S

2018-05-08 13:56 UTC, fixpunkt approved these changes
Looks good!

2018-05-14 13:04 UTC, windaishi commented
I am going to merge this PR into this one: https://github.com/shopware/shopware/pull/1496

2018-05-14 13:06 UTC, merged