Add possibility to configure a price group as "cross article"
VIISON/shopware-4 pull request #78
Opened 2018-04-24 13:49 UTC by windaishi

### 1. Why is this change necessary?
If you assign an article to a price group, the quantity to calculate the discount for the price group is based on how many items of exactly this article are in the basket. It does not consider neither variants of this article nor completely different articles that are in the same price group.

### 2. What does this change do, exactly?
This PR allows you to define a scale of discount across multiple articles. The discount level is calculated depending on the total amount of   (different) articles of the same price group. To achieve this, a price group can be configured to be 'cross article'.

It also adds a line to the price block in the frontend detail page that shows how much articles of this price groups are in the basket already.

### 3. Describe each step to reproduce the issue or behaviour.
N/A

### 4. Please link to the relevant issues (if any).
N/A

### 5. Which documentation changes (if any) need to be made because of this PR?
There section about price groups config should be extended by a paragraph explaining what the config 'cross article' means.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2018-04-24 16:37 UTC, fixpunkt requested changes
Nice work! 🗽

I found some minor things that irk me and the usual grammar mistakes. However, I have no clue about the topic, so maybe we can go through the code together and do a few rounds of testing tomorrow, once you've fixed the issues I've marked up.

@stefanheppenheimer also agreed to do a final round of review on this one once I'm satisified this PR is good to go.

2018-04-24 16:37 UTC, fixpunkt commented on engine/Shopware/Bundle/StoreFrontBundle/Struct/Product/PriceGroup.php
> +    /**
Blank line above missing

2018-04-24 16:37 UTC, fixpunkt commented on engine/Shopware/Controllers/Frontend/Detail.php
> +     * Calculates the total quantity of the item in the basket that belong to a given pricegroup.
> Calculates the total number of items in the basket that belong to a given pricegroup.

2018-04-24 16:37 UTC, fixpunkt commented on engine/Shopware/Core/sBasket.php
> +                GROUP_CONCAT(avoid.customergroupID SEPARATOR "|") as blocked_customer_groups,
`AS`

2018-04-24 16:37 UTC, fixpunkt commented on engine/Shopware/Core/sBasket.php
> +                IFNULL(priceGroup.crossArticle, 0) as priceGroupIsCrossArticle,
`AS`

2018-04-24 16:37 UTC, fixpunkt commented on engine/Shopware/Core/sBasket.php
> +            SELECT
Since this is a heredoc, you should probably indent this all the way to the left (i.e. the way it was before).

2018-04-25 13:21 UTC, fixpunkt approved these changes

2018-04-25 13:22 UTC, fixpunkt commented
Please request @stefanheppenheimer's review once you've fixed the bugs we just found.

2018-04-25 13:53 UTC, windaishi commented
Everythink is fixes now @stefanheppenheimer

2018-04-26 12:06 UTC, stefanheppenheimer requested changes

2018-04-26 12:06 UTC, stefanheppenheimer commented on engine/Shopware/Controllers/Frontend/Detail.php
> +        $this->View()->priceGroupItemQuantityInBasket = Shopware()->Modules()->Basket()->getPriceGroupItemQuantityInBasket($article['pricegroupID']);
I propose to use `numberOfPriceGroupItemsInBasket` to avoid misunderstandings, since the current naming could be misunderstood as the quantity of just one price group item. A even better naming would be `numberOfBasketItemsWithSamePriceGroup` 
As an alternative you could introduce and use an abstract custom term like `priceGroupQuantity` and simply name the property `priceGroupQuantity`omitting the `inBasket` Postfix, which could be derived from the context.

priceGroupItemQuantityInBasket

priceGroupQuantity
priceGroupItemsQuantity
priceGroupBasketItemsQuantity
numberOfPriceGroupItemsInBasket
numberOfBasketItemsWithSamePriceGroup
totalQuantityOfBasketItemsWithSamePriceGroup

2018-04-26 12:06 UTC, stefanheppenheimer commented on engine/Shopware/Controllers/Frontend/Detail.php
> +    public function getPriceGroupBasketQuantityAction()
As a matter of consistency I propose to use the same naming schema used for the view variable: `getNumberOfPriceGroupItemsInBasketAction()`.

2018-04-26 12:06 UTC, stefanheppenheimer commented on engine/Shopware/Core/sBasket.php
> +    IF (priceGroup.crossArticle = 1, IFNULL(priceGroupQuantities.priceGroupQuantity, 0), s_order_basket.quantity) AS priceGroupDiscountQuantity
In my opinion there is no need to use yet another name for the same property. Hence I propose to name this custom attribute `priceGroupQuantity` instead of `priceGroupDiscountQuantity`.

2018-04-26 12:06 UTC, stefanheppenheimer commented on engine/Shopware/Core/sBasket.php
> +    public function getPriceGroupItemQuantityInBasket($priceGroupId) {
See my comments above about the naming.

2018-04-26 12:06 UTC, stefanheppenheimer commented on themes/Frontend/Responsive/frontend/_public/src/js/jquery.price-group-basket-items-quantity.js
> +        onAddArticle: function () {
Please add a short comment describing the methods purpose.

2018-05-02 12:31 UTC, stefanheppenheimer approved these changes

2018-05-03 08:54 UTC, windaishi commented
Closed in favour of https://github.com/shopware/shopware/pull/1654

2018-05-03 08:54 UTC, closed without merging